theme: jekyll-theme-cayman
title: RiSiRi
description: warehouse management plugin
show_downloads: true
github:
  zip_url: https://github.com/ErwinJobse/risiriplugin/archive/0.9.zip
  tar.gz_url: https://github.com/ErwinJobse/risiriplugin/archive/0.9.tar.gz
